---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  #region: ${AWS_REGION}
  region: us-west-2
  version: "1.21"

vpc:
  subnets:
    public:
      us-west-2a: { id: subnet-07593cf01d005fa42 }
      us-west-2b: { id: subnet-0a61c4c91b53cf21b }
      us-west-2c: { id: subnet-0754d608e4c8f9075 }
    private:
      us-west-2a: { id: subnet-0b9e3846a42e9a303 }
      us-west-2b: { id: subnet-05acc9ba198cd4e81 }
      us-west-2c: { id: subnet-095c41614d90919cc }
    
      

nodeGroups:
  - name: general
    instanceType     : t3.small
    volumeSize       : 30
    minSize: 2
    maxSize: 4
    desiredCapacity  : 2
    instanceName     : general
    labels          : { role: general }
    privateNetworking: true
    # https://github.com/weaveworks/eksctl/blob/main/examples/
    ssh: # import public key from file
      # publicKeyPath: ~/.ssh/id_rsa_tests.pub # for Linux
      publicKeyPath: D:\keys\key.pub

    iam:
      withAddonPolicies:
        imageBuilder : true
        autoScaler   : true
        externalDNS  : true
        certManager  : true
        appMesh      : true
        ebs          : true
        fsx          : true
        efs          : true
        albIngress   : true
        xRay         : true
        cloudWatch   : true  
  


  - name: general-spot
    instanceType     : mixed
    instancesDistribution:
      instanceTypes  : ["t3.small", "t3.medium"] 
      maxPrice       : 0.04
    volumeSize       : 30
    minSize          : 2
    maxSize          : 4
    desiredCapacity  : 2
    instanceName     : general-spot
    labels           : { role: general-spot }
    privateNetworking: true
    # https://github.com/weaveworks/eksctl/blob/main/examples/
    ssh: # import public key from file
      # publicKeyPath: ~/.ssh/id_rsa_tests.pub # for Linux
      publicKeyPath: D:\keys\key.pub
  
    iam:
      withAddonPolicies:
        imageBuilder : true
        autoScaler   : true
        externalDNS  : true
        certManager  : true
        appMesh      : true
        ebs          : true
        fsx          : true
        efs          : true
        albIngress   : true
        xRay         : true
        cloudWatch   : true



# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

  #secretsEncryption:
    #keyARN: ${MASTER_ARN}